# Generated by Django 5.2.7 on 2025-10-21 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('idMetodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metodo_Pago',
                'verbose_name_plural': 'Metodos_Pago',
                'db_table': 'Metodos_Pago',
            },
        ),
        migrations.CreateModel(
            name='ModelosAviones',
            fields=[
                ('idModeloAvion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_pasajeros', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo_Avion',
                'verbose_name_plural': 'Modelos_Aviones',
                'db_table': 'Modelos_Aviones',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('asiento', models.CharField(default=None, max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('idTipoIdentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo_Identificacion',
                'verbose_name_plural': 'Tipos_Identificacion',
                'db_table': 'Tipos_Identificacion',
            },
        ),
        migrations.CreateModel(
            name='Aeropuertos',
            fields=[
                ('idAeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fk_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ciudades')),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'db_table': 'Aeropuertos',
            },
        ),
        migrations.CreateModel(
            name='Aviones',
            fields=[
                ('idAvion', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fk_modelo_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.modelosaviones')),
            ],
            options={
                'verbose_name': 'Avion',
                'verbose_name_plural': 'Aviones',
                'db_table': 'Aviones',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fk_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.metodospago')),
                ('fk_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.reservas')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Tiquetes',
            fields=[
                ('idTiquete', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fk_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pagos')),
            ],
            options={
                'verbose_name': 'Tiquete',
                'verbose_name_plural': 'Tiquetes',
                'db_table': 'Tiquetes',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(default=None, max_length=50, null=True)),
                ('segundo_apellido', models.CharField(default=None, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(default=None, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=None, max_length=10, null=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fk_tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tipoidentificacion')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='reservas',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuarios'),
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('idVuelo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_salida', models.DateTimeField()),
                ('fecha_hora_llegada', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fk_aeropuerto_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeropuerto_llegada', to='App.aeropuertos')),
                ('fk_aeropuerto_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeropuerto_salida', to='App.aeropuertos')),
                ('fk_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aviones')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'db_table': 'Vuelos',
            },
        ),
        migrations.AddField(
            model_name='reservas',
            name='fk_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vuelos'),
        ),
    ]
