# Generated by Django 5.2.7 on 2025-10-22 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_vuelos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='fk_pasajero',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasajero_reserva', to='App.usuarios'),
        ),
    ]
