# Generated by Django 5.2.7 on 2025-10-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_reservas_fk_pasajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='es_infante',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
